### ISSUE TITLE
Unable to compile sbnana

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbnana#8] opened 2021-03-17 13:47 UTC
I'm trying to compile `sbnana` on its own, but can't. Tried with `v09_16_00`, `v09_17_00` and `v09_17_02`. They all seem to have the same error.

I'm following the typical recipe of

```
source localProducts*/setup
mrbsetenv
mrb i
```

Is this package supposed to be built differently?

The error in all attempts looks something like this:
```
INFO Parsing source file "/cvmfs/sbnd.opensciencegrid.org/products/sbnd/sbnanaobj/v09_16_03/include/sbnanaobj/StandardRecord/StandardRecord.h" ...
In file included from /cvmfs/sbnd.opensciencegrid.org/products/sbnd/sbnanaobj/v09_16_03/include/sbnanaobj/StandardRecord/StandardRecord.h:10:
In file included from /cvmfs/sbnd.opensciencegrid.org/products/sbnd/sbnanaobj/v09_16_03/include/sbnanaobj/StandardRecord/SRCRTHit.h:7:
In file included from /cvmfs/sbnd.opensciencegrid.org/products/sbnd/sbnanaobj/v09_16_03/include/sbnanaobj/StandardRecord/SRVector3D.h:9:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TVector3.h:16:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TMatrix.h:23:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TMatrixF.h:20:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TMatrixT.h:23:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TMatrixTBase.h:73:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/TString.h:28:
/cvmfs/larsoft.opensciencegrid.org/products/root/v6_22_06a/Linux64bit+3.10-2.17-e19-p383b-prof/include/ROOT/RStringView.hxx:19:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.21//bin/gen_srproxy", line 475, in <module>
    main()
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.21//bin/gen_srproxy", line 433, in main
    decls = pygccxml.parser.parse([input_header], config)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/__init__.py", line 51, in parse
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/project_reader.py", line 264, in read_files
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/source_reader.py", line 299, in read_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/source_reader.py", line 318, in read_cpp_source_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v2_1_0/lib/python3.8/site-packages/pygccxml-2.1.0-py3.8.egg/pygccxml/parser/source_reader.py", line 264, in create_xml_file
RuntimeError: Error occurred while running CASTXML:  status:1
make[2]: *** [sbnana/sbnana/CAFAna/StandardRecord/Proxy/SRProxy.cxx] Error 1
make[1]: *** [sbnana/sbnana/CAFAna/StandardRecord/Proxy/CMakeFiles/StandardRecordProxy.dir/all] Error 2
make: *** [all] Error 2

------------------------------------
ERROR: Stage install / package failed.
------------------------------------

```

**Comment by cjbackhouse** [comment] 2021-03-17 13:53
`string_view` is something to do with a mismatch between the C++ standard ROOT is configured for and what the compiler. But I've never seen it in this context.

Long shot: can you check `which castxml` and `CASTXML_DIR`?

**Comment by cjbackhouse** [comment] 2021-03-17 14:14
Could you try `feature/bckhouse_castxml_guards` in `sbnanaobj`? I think that should work around this problem, though I don't understand the underlying cause or why you seem to be the only one experiencing it.

**Comment by ikatza** [comment] 2021-03-17 16:22
Thanks for getting back so quickly, unfortunately the systems maintenance got in the way and got kicked out of my session. 


```
$ which castxml
/cvmfs/larsoft.opensciencegrid.org/products/castxml/v0_4_2/Linux64bit+3.10-2.17/bin/castxml
$ echo $CASTXML_DIR
/cvmfs/larsoft.opensciencegrid.org/products/castxml/v0_4_2
```

Using the branch with guards helps to get some more progress with the compilation. But now I'm getting errors with `size_t`:

```
INFO Parsing source file "/sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/StandardRecord.h" ...
In file included from /sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/StandardRecord.h:13:
In file included from /sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/SRSlice.h:10:
/sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/SRSliceRecoBranch.h:26:5: error: unknown
      type name 'size_t'; did you mean '__gnu_cxx::size_t'?
    size_t               ntrk;     ///< Number of panora tracks
    ^~~~~~
    __gnu_cxx::size_t
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ext/new_allocator.h:44:14: note:
      '__gnu_cxx::size_t' declared here
  using std::size_t;
```

for some reason it's using some junk `gcc:` **/usr/lib/gcc/x86_64-redhat-linux/4.8.5/...**

No idea why, the one on cvmfs should be picked up:
```
which -a gcc
/cvmfs/larsoft.opensciencegrid.org/products/gcc/v8_2_0/Linux64bit+3.10-2.17/bin/gcc
/usr/bin/gcc
```

At this point, unless there's something obvious missing. Maybe the best would be to wait until maintenance is completely finish in case this last issue is related to that.

**Comment by cjbackhouse** [comment] 2021-03-17 17:48
I wonder if this wrong gcc was the cause of the original issue as well?

**Comment by cjbackhouse** [comment] 2021-03-17 17:54
What do you get for this?
```$ castxml -v
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: 
Found candidate GCC installation: /cvmfs/larsoft.opensciencegrid.org/products/gcc/v8_2_0/Linux64bit+3.10-2.17/lib/gcc/x86_64-pc-linux-gnu/8.2.0
Selected GCC installation: /cvmfs/larsoft.opensciencegrid.org/products/gcc/v8_2_0/Linux64bit+3.10-2.17/lib/gcc/x86_64-pc-linux-gnu/8.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64```

**Comment by ikatza** [comment] 2021-03-18 15:00
Looks the same as yours:

```
 $  castxml -v
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir:
Found candidate GCC installation: /cvmfs/larsoft.opensciencegrid.org/products/gcc/v8_2_0/Linux64bit+3.10-2.17/lib/gcc/x86_64-pc-linux-gnu/8.2.0
Selected GCC installation: /cvmfs/larsoft.opensciencegrid.org/products/gcc/v8_2_0/Linux64bit+3.10-2.17/lib/gcc/x86_64-pc-linux-gnu/8.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

**Comment by ikatza** [comment] 2021-03-18 15:10
I've tried compiling using clang with qual `c7` and it builds OK. I'm including your branch with guards.

**Comment by cjbackhouse** [comment] 2021-03-18 15:16
I'm pretty confused what is going on here. Obviously pygccxml/castxml somehow picks up the wrong includes from a wrong version of gcc. Your environment looks ok so far as we can tell, and I don't think anyone else has hit this.
Could you maybe give a sequence of steps to check out and build things that runs into this that I can try out for myself?

**Comment by ikatza** [comment] 2021-03-18 17:28
Since you've mentioned that I'm the only one experiencing this I figured to take a look at the environmental variables on my session. Trimming `PATH` out of all the custom stuff that I put allows me to build `sbnana` with gcc again. There's a few stuff in my path that might be troublesome, but all of it appears after the block of cvmfs products.

Going back to the error:
```
In file included from /sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/SRSlice.h:10:
/sbnd/app/users/icaza/work/sbnana/srcs/sbnanaobj/sbnanaobj/StandardRecord/SRSliceRecoBranch.h:26:5: error: unknown type name 'size_t'; did you mean '__gnu_cxx::size_t'?
    size_t               ntrk;     ///< Number of panora tracks
    ^~~~~~
    __gnu_cxx::size_t
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ext/new_allocator.h:44:14: note: '__gnu_cxx::size_t' declared here
  using std::size_t;
             ^
```

I'm surprised of the long path it took to get to `new_allocator.h`, note that `/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ext/new_allocator.h` is in fact `/usr/include/c++/4.8.5/ext/new_allocator.h`

Lastly, this is the only product where my local environment collides with the compilation.

**Comment by cjbackhouse** [comment] 2021-03-18 17:34
A different approach - does adding `#include <cstddef>` to the top of SRSliceRecoBranch.h make any difference?

**Comment by ikatza** [comment] 2021-03-18 17:52
Yeah, that solves it. Thanks.

**Comment by wesketchum** [comment] 2021-04-02 14:44
Closing.

**Closed by wesketchum** 2021-04-02 14:44 UTC
